### ISSUE TITLE
Pull Request #68 not compiling, missing references

### ISSUE THREAD

**Issue by Chulepa** [libgdx-jam/GDXJam#69]
I don't know why the merge was made, since it doesn't compile. It is missing the reference Assests.getInstance().fonts , that is used on GUISystem.java. I think it was @Twiebs  who was cleaning the code and some assets, so, could you reference the fonts in other way, or clean also this part of the code?

**Comment by alex-place** [comment]
Fixed with commit https://github.com/libgdx-jam/GDXJam/commit/f9435fa2789dd09bb2ef5e5d58dd9bfe843e3221

**Comment by Chulepa** [comment]
thanks
