### ISSUE TITLE
Asset not loaded: assets.atlas

### ISSUE THREAD

**Issue by alex-place** [libgdx-jam/GDXJam#88]
If this is set to true:
private static boolean rebuildAtlas = true;
The TexturePacker runs every time and sometimes causes an error in eclipse that forces you to refresh before running the game.

**Comment by Twiebs** [comment]
This isn't really a bug.  Its just the way it works.  You always need to manually refresh the android project if you add an asset.  When the TexturerPacker rebuilds the atlas the android project is not automatically refreshed and still thinks the atlas file is the same as the old one.  There might be a way to create a run tool that auto refreshes the android project.  I have never looked into it before.

**Comment by alex-place** [comment]
All I'm saying is it would save time to not have to refresh and change the rebuild option. I tried to use packer.processIfModified to no success.
